import styles from './globals.css'

export const metadata = {
  title: 'ChimpSocial',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.className}>{children}</body>
    </html>
  )
}
